name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 3.0.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 6f24c8f57e4549edbf7d68a021d1d94371c23f3f
      path: packages/audioplayers_android/
  audioplayers_darwin:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 6f24c8f57e4549edbf7d68a021d1d94371c23f3f
      path: packages/audioplayers_darwin/
  audioplayers_linux:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 6f24c8f57e4549edbf7d68a021d1d94371c23f3f
      path: packages/audioplayers_linux/
  audioplayers_platform_interface: ^4.0.0
  audioplayers_web:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 6f24c8f57e4549edbf7d68a021d1d94371c23f3f
      path: packages/audioplayers_web/
  audioplayers_windows:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 6f24c8f57e4549edbf7d68a021d1d94371c23f3f
      path: packages/audioplayers_windows/
  flutter:
    sdk: flutter
  http: ^0.13.5
  path_provider: ^2.0.12
  synchronized: ^3.0.1
  uuid: ^3.0.7

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

